import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1536,height:1024},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.CAMX_QA_URL??'http://localhost:5173');
await page.waitForFunction(()=>window.camxStudio?.parts.size===17,null,{timeout:30000});
await page.locator('#loading').waitFor({state:'hidden'});await page.waitForTimeout(700);
await mkdir('../docs/design',{recursive:true});
assert.equal(await page.locator('h1').textContent(),'Made to move.');
for(const [id,value]of [['pan',35],['tilt',-20],['explode',70]])await page.locator('#'+id).evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},value);
assert.ok(await page.evaluate(()=>window.camxStudio.pan.rotation.y<0));
assert.ok(await page.evaluate(()=>window.camxStudio.tilt.rotation.x<0));
assert.equal(await page.locator('#pan-value').textContent(),'35°');
assert.ok(await page.evaluate(()=>window.camxStudio.parts.get('lid').position.y>10));
await page.locator('#hardware').uncheck();assert.equal(await page.evaluate(()=>window.camxStudio.parts.get('pan_servo').visible),false);
await page.locator('#wireframe').check();assert.equal(await page.evaluate(()=>{let v=false;window.camxStudio.parts.get('base').traverse(o=>{if(o.isMesh)v=o.material.wireframe;});return v;}),true);
await page.locator('summary').click();await page.locator('[data-part="lid"]').uncheck();assert.equal(await page.evaluate(()=>window.camxStudio.parts.get('lid').visible),false);
for(const v of ['front','side','top','perspective']){await page.locator(`[data-view="${v}"]`).click();assert.equal(await page.locator(`[data-view="${v}"]`).getAttribute('aria-pressed'),'true');}
await page.locator('#reset').click();assert.ok(await page.evaluate(()=>Math.abs(window.camxStudio.pan.rotation.y)<1e-8));assert.equal(await page.evaluate(()=>window.camxStudio.parts.get('lid').visible),true);
await page.locator('summary').click();await page.waitForTimeout(200);
for(const href of ['models/camx.glb','downloads/camx-files.zip','downloads/assembly/print_layout.3mf','downloads/assembly/camx.step','guide/build.html'])assert.equal((await page.request.get(new URL(href,page.url()).href)).status(),200,href);
await page.screenshot({path:'../docs/design/viewer-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');
await page.screenshot({path:'../docs/design/viewer-mobile.png',fullPage:true});
await page.locator('a[href="guide/build.html"]').first().click();await page.locator('h1').waitFor();assert.match(await page.locator('h1').textContent(),/CAMX assembly/);
assert.deepEqual(errors,[]);
const result={passed:true,desktop:[1536,1024],mobile:[390,844],checks:['17 CAD part groups loaded','pan/tilt pivots','explode transforms','hardware visibility','wireframe','per-part visibility','four camera views','reset','download links HTTP 200','mobile no overflow','guide navigation','zero page errors'],method:'Playwright Chromium fallback; IAB unavailable'};
await writeFile('../docs/design/viewer-qa.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
